apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: KDEV_NAME
  namespace: KDEV_NAMESPACE
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
