apiVersion: v1
kind: Pod
metadata:
  name: KDEV_NAME
  namespace: NAMESPACE
spec:
  serviceAccountName: KDEV_NAME
  serviceAccount: KDEV_NAME
  restartPolicy: Never
  containers:
  - name: KDEV_NAME
    image: ubuntu
    command: [ "tail", "-f", "/dev/null" ]
    securityContext:
      privileged: true
      capabilities:
        add:
          - SYS_ADMIN

